Padim exclude gauss
OpenAOI/anodet pull request #35
Opened 2023-10-02 12:37 UTC by wlinds

Set gaussian_blur as arg (bool) for padim.predict method (defaults to True)

2023-10-10 18:05 UTC, antonemanuel commented on anodet/padim.py
> +
Why are there two lines here?

2023-10-10 18:07 UTC, antonemanuel commented on anodet/feature_extraction.py
> +from torchvision.models import resnet18, ResNet18_Weights, wide_resnet50_2, Wide_ResNet50_2_Weights
Did you mean to include this in the pr? I saw that you had another commit with these changes. If you bother I think it's nicer with two different pr's, to keep them simple.

2023-10-10 18:07 UTC, antonemanuel requested changes
See comments in code

2023-11-16 10:38 UTC, wlinds commented on anodet/padim.py
> +
linter

2023-11-16 17:26 UTC, merged